import { NextResponse } from 'next/server';
import { getServerSession } from "next-auth";
import dbConnect from '@/lib/mongodb';
import Project from '@/models/Project';
import { authOptions } from '@/app/api/auth/[...nextauth]/route'; // Assuming you exported this

export async function POST(req: Request) {
  try {
    // 1. Authenticate the user
    const session = await getServerSession(authOptions);
    if (!session || !session.user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // 2. Parse request body
    const { title, description, codeSnippet, language, tags, thumbnailUrl, visibility } = await req.json();

    // 3. Validation
    if (!title || !codeSnippet || !language) {
      return NextResponse.json({ error: 'Missing required fields' }, { status: 400 });
    }

    // 4. Connect to database
    await dbConnect();

    // 5. Create the project
    const newProject = await Project.create({
      title,
      description,
      codeSnippet,
      language,
      tags,
      thumbnailUrl, // This URL would be generated by your image upload service
      author: (session.user as any).id, // Assuming ID is mapped in session
      visibility: visibility || 'Public',
    });

    return NextResponse.json(newProject, { status: 201 });
  } catch (error) {
    console.error('Project creation error:', error);
    return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
  }
}
